services:
  grafana:
    image: grafana/grafana:12.0.0
    restart: unless-stopped
    user: "0:0"
    environment:
      - GF_ANALYTICS_ENABLED=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=false
      - GF_ANALYTICS_FEEDBACK_LINKS_ENABLED=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_DATABASE_LOG_QUERIES=true
      # Disable alerting for quieter log
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_EXECUTE_ALERTS=false
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning:ro"
      - "./grafana/dashboards:/var/lib/grafana/dashboards:ro"
      - "grafana-data:/var/lib/grafana"
    deploy:
      resources:
        limits:
          memory: 500M
    ports:
      - 3012:3000

volumes:
  grafana-data: